server:
  servlet:
    context-path: /locadora-vhs/api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/locadora_vhs # Conexão com o banco de dados
    username: postgres
    password: postgres
  jpa:
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         "[format_sql]": true
     show-sql: true
     hibernate:
      ddl-auto: none # Desabilita a auto-criação do hibernate que cria as tabelas com base nas entities
  sql:
    init:
      mode: never  # Para que o Spring utilize os scripts de inicialização da base de dados (schema.sql e data.sql)
      continue-on-error: true # Quando o banco já foi inicializado ele dá erro na próxima vez que tentar inicializar
  main:
    banner-mode: off # Desabilita o banner do spring no output